language: cpp
compiler:
  - clang
notifications:
  email: true
env:
  matrix:
    #- JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
install:
  - sudo apt-get install libpcre3-dev julia -y
  - julia -e 'versioninfo()'
  - julia -e 'Pkg.add("Coverage")'
  - julia -e 'Pkg.clone(pwd())'
script:
  #- julia -e 'Pkg.test("LinearExpressions")'
  - julia --code-coverage pkgtest.jl
after_success:
  - julia -e 'cd(Pkg.dir("LinearExpressions")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
