language: julia
julia:
  - 1.0
os:
  - linux
  - osx

notifications:
  email: true

# coveralls: true
after_success:
- julia -e 'using Pkg; cd(Pkg.dir("LinearExpressions")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
