name = "LinearExpressions"
uuid = "10c43afe-d24e-11e8-1e5e-d9ae8d9c0940"
authors = ["Cristóvão D. Sousa <crisjss@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = ">=0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
